"""Generate the cross-language codec fixtures.

The Python codecs are the reference implementation; the TypeScript client only
mirrors them. This script freezes a set of payloads produced by the reference
into a JSON file that the Vitest suites decode and the pytest suite re-derives,
so neither side can drift without a test going red.

Run it from the repository root after any protocol change::

    python -m ascii_city.tools.make_fixtures
"""

from __future__ import annotations

import base64
import json
from pathlib import Path

from ..domain.chat import ChatMessage, ChatScope
from ..domain.constants import ANIMATION_RUN, ANIMATION_WALK
from ..domain.player import PlayerState
from ..domain.world import Building, Prop, Road, SpawnPoint, WorldTile
from ..infrastructure import wire_codec as wire
from ..infrastructure.tile_codec import encode_tile

FIXTURE_PATH = (
    Path(__file__).resolve().parents[1] / "frontend" / "src" / "__fixtures__" / "protocol.json"
)

TILE_CELLS = 8


def _b64(payload: bytes) -> str:
    return base64.b64encode(payload).decode("ascii")


def _sample_tile() -> WorldTile:
    """A deliberately tiny tile: the codec is what is under test, not the city."""
    area = TILE_CELLS * TILE_CELLS
    collision = bytearray(area)
    heights = bytearray(area)
    styles = bytearray(area)
    for index in range(area):
        collision[index] = (index % 5) % 4
        heights[index] = (index * 7) % 200
        styles[index] = (index * 13) % 256

    return WorldTile(
        id="fixture:3:5",
        version=7,
        tile_x=3,
        tile_y=5,
        cells=TILE_CELLS,
        cell_size=2.0,
        collision=collision,
        heights=heights,
        styles=styles,
        buildings=(
            Building(
                id=1,
                footprint=(0, 0, 3, 0, 3, 4, 0, 4),
                height=42,
                min_height=0,
                levels=14,
                roof_type=2,
                category=4,
                facade_style=3,
                window_style=2,
                color=9,
                walkable=False,
                interior_id=None,
            ),
            Building(
                id=2,
                footprint=(5, 5, 7, 5, 7, 7, 5, 7),
                height=9,
                min_height=2,
                levels=3,
                roof_type=1,
                category=1,
                facade_style=0,
                window_style=1,
                color=4,
                walkable=True,
                interior_id="lobby",
            ),
        ),
        roads=(
            Road(
                id=1,
                centerline=(0, 4, 7, 4),
                width=6.5,
                type=1,
                walkable=True,
                surface_style=2,
                name="Neon Avenue",
            ),
            Road(
                id=2,
                centerline=(4, 0, 4, 7),
                width=3.0,
                type=0,
                walkable=True,
                surface_style=1,
                name=None,
            ),
        ),
        props=(Prop(id=1, x=2, y=6, kind=3), Prop(id=2, x=6, y=1, kind=0)),
        spawn_points=(
            SpawnPoint(x=1, y=1, heading=0.0),
            SpawnPoint(x=6, y=6, heading=3.141592653589793),
        ),
    )


def _player(identifier: int, nickname: str, **overrides) -> PlayerState:
    fields = dict(
        id=identifier,
        nickname=nickname,
        color=identifier % 12,
        x=112.5,
        y=64.25,
        z=1.7,
        yaw=1.25,
        pitch=-0.4,
        animation=ANIMATION_WALK,
    )
    fields.update(overrides)
    return PlayerState(**fields)


def build() -> dict:
    viewer = _player(1, "amber-lantern")
    others = [
        (_player(2, "violet-conduit", x=98.0, y=70.5, yaw=4.5, pitch=0.9), False),
        (
            _player(3, "quiet-rebar", x=300.0, y=12.0, yaw=0.0, pitch=0.0, animation=ANIMATION_RUN),
            True,
        ),
    ]

    message = ChatMessage(
        id=987654321,
        sender_id=2,
        nickname="violet-conduit",
        text="the tower on 4th is lit again <grin>",
        scope=ChatScope.PROXIMITY,
        created_at=1764792000.5,
    )

    return {
        "note": "Generated by ascii_city/tools/make_fixtures.py. Do not edit by hand.",
        "scalars": {
            "positions": [
                {"metres": value, "encoded": wire.encode_position(value)}
                for value in (0.0, 0.005, 1.0, 112.5, 655.34, 655.35, 900.0, -3.0)
            ],
            "yaw": [
                {"radians": value, "encoded": wire.encode_yaw(value)}
                for value in (0.0, 1.25, 3.141592653589793, 6.0, 7.5, -1.0)
            ],
            "pitch": [
                {"radians": value, "encoded": wire.encode_pitch(value)}
                for value in (0.0, 0.5, -0.4, 1.2, -1.2, 4.0, -4.0)
            ],
        },
        "clientFrames": {
            "input": {
                "command": {
                    "sequence": 4242,
                    "forward": 1.0,
                    "strafe": -0.5,
                    "yaw": 1.25,
                    "pitch": -0.4,
                    "sprint": True,
                    "clientTime": 123456,
                },
                # Byte-for-byte what the server's decoder expects to receive.
                "encoded": _b64(
                    bytes([wire.MSG_INPUT])
                    + wire._INPUT.pack(
                        4242, 100, -50, wire.encode_yaw(1.25), wire.encode_pitch(-0.4), 1, 123456
                    )
                ),
            },
            "chat": {
                "scope": "proximity",
                "text": "meet me under the sign",
                "encoded": _b64(
                    bytes([wire.MSG_CHAT, 1])
                    + len("meet me under the sign".encode()).to_bytes(2, "little")
                    + "meet me under the sign".encode()
                ),
            },
            "ping": {
                "clientTime": 77777,
                "encoded": _b64(bytes([wire.MSG_PING]) + (77777).to_bytes(4, "little")),
            },
        },
        "serverFrames": {
            "welcome": {
                "encoded": _b64(
                    wire.encode_welcome(
                        player=viewer,
                        simulation_hz=20,
                        snapshot_hz=20,
                        server_time_ms=1700000000,
                        world_id="demo",
                        world_version=3,
                        tiles_x=2,
                        tiles_y=2,
                        tile_cells=128,
                        cell_size=2.0,
                    )
                ),
                "expected": {
                    "playerId": viewer.id,
                    "color": viewer.color,
                    "nickname": viewer.nickname,
                    "simulationHz": 20,
                    "snapshotHz": 20,
                    "serverTimeMs": 1700000000,
                    "tilesX": 2,
                    "tilesY": 2,
                    "tileCells": 128,
                    "cellSize": 2.0,
                    "worldVersion": 3,
                    "worldId": "demo",
                },
            },
            "snapshot": {
                "encoded": _b64(
                    wire.encode_snapshot(
                        tick=90210, ack_sequence=4242, viewer=viewer, entries=others
                    )
                ),
                "expected": {
                    "tick": 90210,
                    "ackSequence": 4242,
                    "entryCount": 2,
                    "entries": [
                        {"id": 2, "simplified": False, "animation": ANIMATION_WALK},
                        {"id": 3, "simplified": True, "animation": ANIMATION_RUN},
                    ],
                },
            },
            "chat": {
                "encoded": _b64(wire.encode_chat(message)),
                "expected": {
                    "id": message.id,
                    "senderId": message.sender_id,
                    "nickname": message.nickname,
                    "text": message.text,
                    "scope": "proximity",
                    "createdAt": message.created_at,
                },
            },
            "notice": {
                "encoded": _b64(wire.encode_notice(wire.NOTICE_RATE_LIMIT, "Slow down.")),
                "expected": {"code": wire.NOTICE_RATE_LIMIT, "text": "Slow down."},
            },
            "rosterSync": {
                "encoded": _b64(wire.encode_roster_sync([viewer, others[0][0], others[1][0]])),
                "expected": {
                    "members": [
                        {"id": 1, "nickname": "amber-lantern", "color": 1},
                        {"id": 2, "nickname": "violet-conduit", "color": 2},
                        {"id": 3, "nickname": "quiet-rebar", "color": 3},
                    ]
                },
            },
            "rosterAdd": {
                "encoded": _b64(wire.encode_roster_add(others[0][0])),
                "expected": {"id": 2, "nickname": "violet-conduit", "color": 2},
            },
            "rosterRemove": {
                "encoded": _b64(wire.encode_roster_remove(4242)),
                "expected": {"id": 4242},
            },
            "pong": {
                "encoded": _b64(wire.encode_pong(77777, 1700000000)),
                "expected": {"clientTime": 77777, "serverTimeMs": 1700000000},
            },
        },
        "tile": {
            "encoded": _b64(encode_tile(_sample_tile())),
            "expected": {
                "id": "fixture:3:5",
                "version": 7,
                "tileX": 3,
                "tileY": 5,
                "cells": TILE_CELLS,
                "cellSize": 2.0,
                "buildingCount": 2,
                "roadCount": 2,
                "propCount": 2,
                "spawnCount": 2,
                "firstBuilding": {
                    "id": 1,
                    "height": 42,
                    "levels": 14,
                    "roofType": 2,
                    "category": 4,
                    "facadeStyle": 3,
                    "windowStyle": 2,
                    "color": 9,
                    "walkable": False,
                    "hasInterior": False,
                    "footprint": [0, 0, 3, 0, 3, 4, 0, 4],
                },
                "secondBuilding": {"id": 2, "walkable": True, "hasInterior": True},
                "firstRoad": {"id": 1, "width": 6.5, "type": 1, "name": "Neon Avenue"},
                "secondRoadName": None,
                "collisionHead": [(index % 5) % 4 for index in range(8)],
                "heightsHead": [(index * 7) % 200 for index in range(8)],
                "stylesHead": [(index * 13) % 256 for index in range(8)],
            },
        },
    }


def main() -> None:
    FIXTURE_PATH.parent.mkdir(parents=True, exist_ok=True)
    FIXTURE_PATH.write_text(json.dumps(build(), indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {FIXTURE_PATH.relative_to(Path.cwd())}")


if __name__ == "__main__":
    main()
