"""Порт хранилища control-plane API (Worker-прокси + админка + события)."""

from __future__ import annotations

from datetime import datetime
from typing import Any, Protocol

from another_admin.domain.models import AdminRecord, ClientRecord, PingTarget


class ControlPlaneStore(Protocol):
    async def find_client(self, client_id: str) -> ClientRecord | None: ...

    async def find_enrollment_by_token_hash(
        self, token_hash: str
    ) -> tuple[str, datetime] | None: ...

    async def bind_device_identity(
        self,
        client_id: str,
        public_key_hex: str,
        vless_user_id_hex: str,
        public_key_mldsa65_hex: str | None = None,
    ) -> None: ...

    async def consume_enrollment_token(self, token_hash: str) -> None: ...

    async def increment_usage(self, client_id: str, bytes_delta: int) -> None: ...

    async def create_client_stub(
        self,
        comment: str,
        quota_limit_bytes: int,
        enrollment_token_hash: str,
        expires_at: datetime,
    ) -> str: ...

    async def add_client_stub(
        self,
        user_id: str,
        comment: str,
        quota_limit_bytes: int,
        enrollment_token_hash: str,
        expires_at: datetime,
    ) -> str: ...

    async def list_clients(self) -> list[ClientRecord]: ...

    async def set_banned(self, client_id: str, banned: bool) -> None: ...

    async def delete_client(self, client_id: str) -> bool: ...

    async def get_admin(self, admin_id: str) -> AdminRecord | None: ...

    async def insert_admin(self, record: AdminRecord) -> None: ...

    async def replace_admin(self, expected_seq: int, record: AdminRecord) -> bool: ...

    async def put_challenge(self, challenge_hex: str, expires_at: datetime) -> None: ...

    async def consume_challenge(self, challenge_hex: str) -> bool: ...

    async def get_ping_targets(self) -> list[PingTarget]: ...

    async def set_ping_targets(self, targets: list[PingTarget]) -> None: ...

    async def append_event(self, event: dict[str, Any]) -> str: ...

    async def list_events(self, *, limit: int = 100, unacked_only: bool = False) -> list[dict[str, Any]]: ...

    async def ack_event(self, event_id: str) -> bool: ...

    async def upsert_session(self, session: dict[str, Any]) -> str: ...

    async def list_sessions(self, *, active_within_s: int = 180) -> list[dict[str, Any]]: ...

    async def close_session(self, *, client_id: str, ip_hash: str, bytes_delta: int = 0) -> bool: ...

    async def get_alert_thresholds(self) -> dict[str, Any]: ...

    async def set_alert_thresholds(self, thresholds: dict[str, Any]) -> None: ...

    async def get_investigation_mode(self) -> bool: ...

    async def set_investigation_mode(self, enabled: bool) -> None: ...

    async def create_installer_job(self, job: dict[str, Any]) -> str: ...

    async def get_installer_job(self, job_id: str) -> dict[str, Any] | None: ...

    async def update_installer_job(self, job_id: str, fields: dict[str, Any]) -> bool: ...
