/**
 * The client half of the cross-language parity check.
 *
 * `age/tools/make_fixtures.py` records what the Python reference produces; pytest
 * proves that file still matches Python, and this suite proves it matches TypeScript.
 * Between them the two implementations are pinned to each other without either needing
 * to run the other.
 *
 * Terrain is the reason this matters. The client generates its own tiles from the world
 * seed rather than receiving them, so a single disagreeing tile is a player walking into
 * a wall nobody else can see.
 */

import { describe, expect, it } from 'vitest'

import fixtures from '../__fixtures__/parity.json'
import { PROTOCOL_VERSION } from '../domain/constants'
import { isWalkable, blocksSight, Tile } from '../domain/tiles'
import {
  chunkSeed,
  combine,
  hashString,
  hubChunkSeed,
  mix64,
  tileHash,
  unitFloat,
} from './hashing'
import { fractal, gradientNoise, ridged, scatterValue } from './noise'
import { SpaceType, WorldGenerator, type ChunkAddress } from './generator'

const WORLD_SEED = BigInt(fixtures.worldSeed)

// Doubles are exact across both languages in practice, since the operation order is the
// same. The tolerance exists so a difference in how a literal is folded cannot fail the
// build, and it is far tighter than anything that could change a threshold decision.
const EPSILON = 1e-12

describe('the fixture itself', () => {
  it('was generated by the protocol version this client speaks', () => {
    expect(fixtures.protocolVersion).toBe(PROTOCOL_VERSION)
  })
})

describe('hashing', () => {
  it('reproduces every mix64 vector', () => {
    for (const vector of fixtures.hashing.mix64) {
      expect(mix64(BigInt(vector.input)).toString()).toBe(vector.output)
    }
  })

  it('reproduces every combine vector', () => {
    for (const vector of fixtures.hashing.combine) {
      const [seed, a, b, c] = vector.args
      expect(combine(BigInt(seed as string), a as number, b as number, c as number).toString()).toBe(
        vector.output,
      )
    }
  })

  it('hashes strings the same way, including non-ASCII', () => {
    for (const vector of fixtures.hashing.hashString) {
      expect(hashString(vector.input).toString()).toBe(vector.output)
    }
  })

  it('derives the same chunk seeds', () => {
    for (const vector of fixtures.hashing.chunkSeed) {
      const [seed, edge, segment, lane, tier] = vector.args
      expect(
        chunkSeed(
          BigInt(seed as string),
          edge as string,
          segment as number,
          lane as number,
          tier as number,
        ).toString(),
      ).toBe(vector.output)
    }
  })

  it('derives the same hub chunk seeds', () => {
    for (const vector of fixtures.hashing.hubChunkSeed) {
      const [seed, hub, cx, cy] = vector.args
      expect(
        hubChunkSeed(BigInt(seed as string), hub as number, cx as number, cy as number).toString(),
      ).toBe(vector.output)
    }
  })

  it('converts to the unit interval identically', () => {
    for (const vector of fixtures.hashing.unitFloat) {
      expect(unitFloat(BigInt(vector.input))).toBeCloseTo(vector.output, 15)
    }
  })

  it('reproduces every tile hash', () => {
    for (const vector of fixtures.hashing.tileHash) {
      const [seed, x, y, salt] = vector.args
      expect(
        tileHash(BigInt(seed as string), x as number, y as number, salt as number).toString(),
      ).toBe(vector.output)
    }
  })

  it('never leaves the 64-bit range', () => {
    // The masking is the whole trick: an unmasked intermediate would silently produce a
    // different number and desynchronise the terrain with no error anywhere.
    const limit = 1n << 64n
    const seeds = [mix64(WORLD_SEED), combine(WORLD_SEED, -1, -1, 0), hashString('main')]
    for (const value of seeds) {
      expect(value).toBeGreaterThanOrEqual(0n)
      expect(value).toBeLessThan(limit)
    }
  })
})

describe('noise', () => {
  it('reproduces the gradient field', () => {
    for (const vector of fixtures.noise.gradientNoise) {
      expect(gradientNoise(BigInt(vector.seed), vector.x, vector.y)).toBeCloseTo(vector.output, 12)
    }
  })

  it('reproduces the fractal field at every octave count in use', () => {
    for (const vector of fixtures.noise.fractal) {
      const actual = fractal(BigInt(vector.seed), vector.x, vector.y, vector.octaves, vector.frequency)
      expect(Math.abs(actual - vector.output)).toBeLessThan(EPSILON)
    }
  })

  it('reproduces the ridged field the rivers threshold', () => {
    for (const vector of fixtures.noise.ridged) {
      const actual = ridged(BigInt(vector.seed), vector.x, vector.y, vector.octaves, vector.frequency)
      expect(Math.abs(actual - vector.output)).toBeLessThan(EPSILON)
    }
  })

  it('reproduces the scatter rolls that place every prop', () => {
    for (const vector of fixtures.noise.scatterValue) {
      expect(scatterValue(BigInt(vector.seed), vector.x, vector.y, vector.salt)).toBeCloseTo(
        vector.output,
        15,
      )
    }
  })
})

// --- terrain ----------------------------------------------------------------

function addressOf(raw: (typeof fixtures.chunks)[number]['address']): ChunkAddress {
  return {
    spaceType: raw.spaceType,
    hubId: raw.hubId ?? undefined,
    chunkX: raw.chunkX,
    chunkY: raw.chunkY,
    edgeId: raw.edgeId ?? undefined,
    segmentIndex: raw.segmentIndex,
    laneOffset: raw.laneOffset,
    tierMin: raw.tierMin,
  }
}

describe('the chunk generator', () => {
  const generator = new WorldGenerator(WORLD_SEED)

  it('produces the same tiles as the server for every fixture chunk', () => {
    for (const chunk of fixtures.chunks) {
      const tiles = generator.generate(addressOf(chunk.address))
      // Compared row by row rather than as a hash, so a failure says which tiles
      // differ instead of only that something did.
      expect(Array.from(tiles.slice(0, 32)), `${chunk.key} first row`).toEqual(chunk.firstRow)
      expect(Array.from(tiles.slice(16 * 32, 17 * 32)), `${chunk.key} centre row`).toEqual(
        chunk.centreRow,
      )
    }
  })

  it('agrees on the chunk key, which is what the wire uses to name a chunk', () => {
    for (const chunk of fixtures.chunks) {
      const tiles = generator.generate(addressOf(chunk.address))
      expect(tiles.length).toBe(32 * 32)
    }
  })

  it('classifies each chunk into the same biome', () => {
    for (const chunk of fixtures.chunks) {
      const fields = generator.fieldsFor(addressOf(chunk.address))
      expect(fields.biome, `${chunk.key} biome`).toBe(chunk.biome)
      expect(Math.abs(fields.elevation - chunk.elevation)).toBeLessThan(EPSILON)
      expect(Math.abs(fields.temperature - chunk.temperature)).toBeLessThan(EPSILON)
      expect(Math.abs(fields.moisture - chunk.moisture)).toBeLessThan(EPSILON)
    }
  })

  it('is deterministic across instances, not merely cached', () => {
    // The cache would hide a seeded-state bug: a second generator has to agree with the
    // first from cold.
    const other = new WorldGenerator(WORLD_SEED)
    const address = addressOf(fixtures.chunks[0].address)
    expect(Array.from(other.generate(address))).toEqual(Array.from(generator.generate(address)))
  })

  it('gives a different world for a different seed', () => {
    const other = new WorldGenerator(WORLD_SEED + 1n)
    const address = addressOf(fixtures.chunks[0].address)
    expect(Array.from(other.generate(address))).not.toEqual(Array.from(generator.generate(address)))
  })

  it('keeps the corridor road continuous across a chunk seam', () => {
    // The road is a function of the along-coordinate alone. If it were sampled per
    // chunk it would step at every multiple of 32, which is exactly what this catches.
    let previous = generator.roadOffset(0)
    for (let along = 1; along <= 96; along += 1) {
      const current = generator.roadOffset(along)
      expect(Math.abs(current - previous), `road jumped at ${along}`).toBeLessThan(0.5)
      previous = current
    }
  })

  it('puts a walkable road down the middle of a corridor chunk', () => {
    // Not a parity assertion but a playability one: if the corridor generated as
    // impassable terrain the demo would be unplayable at some seeds, and no digest
    // comparison would notice.
    const tiles = generator.generate({
      spaceType: SpaceType.EDGE,
      edgeId: 'main',
      segmentIndex: 0,
      laneOffset: 0,
      tierMin: 0,
    })
    const road = Array.from(tiles).filter((tile) => tile === Tile.DIRT_ROAD).length
    expect(road).toBeGreaterThan(0)
  })

  it('leaves most of a hub chunk walkable', () => {
    const tiles = generator.generate({ spaceType: SpaceType.HUB, hubId: 0, chunkX: 0, chunkY: 0 })
    const walkable = Array.from(tiles).filter(isWalkable).length
    expect(walkable / tiles.length).toBeGreaterThan(0.5)
  })

  it('does not generate the same terrain for hub 0 and corridor segment 0', () => {
    // Both sit at the origin of their own space, and with the hub offsets starting at
    // zero they sampled the identical patch of noise.
    const hub = Array.from(
      generator.generate({ spaceType: SpaceType.HUB, hubId: 0, chunkX: 0, chunkY: 0 }),
    )
    const edge = Array.from(
      generator.generate({
        spaceType: SpaceType.EDGE,
        edgeId: 'main',
        segmentIndex: 0,
        laneOffset: 0,
        tierMin: 0,
      }),
    )
    expect(hub).not.toEqual(edge)
  })
})

describe('tile predicates', () => {
  it('agrees with the server on what blocks movement', () => {
    expect(isWalkable(Tile.GRASS)).toBe(true)
    expect(isWalkable(Tile.DIRT_ROAD)).toBe(true)
    expect(isWalkable(Tile.WATER)).toBe(false)
    expect(isWalkable(Tile.WALL_STONE)).toBe(false)
  })

  it('lets sight cross water even though movement cannot', () => {
    // An archer has to be able to shoot over a river nobody can walk across.
    expect(blocksSight(Tile.WATER)).toBe(false)
    expect(isWalkable(Tile.WATER)).toBe(false)
    expect(blocksSight(Tile.TREE)).toBe(true)
  })
})
